- hosts: all
  tasks:
    - name: Repository 
     yum: state=present name={{ item }}
     with_items:
     - php
     - php-fpm
     - php-mysql
     - nginx
     - mariadb-server
     - mariadb
     - mysql
     - rsync
     become: true

  #EPEL
  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

  #firewall
  - firewalld:
      service: https
      permanent: yes
      state: enabled
      immediate: yes
    become: true

  - firewalld:
      zone: dmz
      service: http
      permanent: yes
      state: enabled
      immediate: yes
    become: true
    
  #nginx
  - name: install nginx
    package:
      name: nginx
      state: present

  - name: copy nginx to configuration file
    copy:
      src: /provisioning/setup/nginx.conf
      dest: /etc/nginx.conf
      owner: admin
      group: admin
      mode: 0644

  - name: Start service nginx
    service:
      name: nginx
      state: started
  
  #PHP
  - name: install php
    package:
      name: php
      state: present

  - name: install php-fpm
    package:
      name: php-fpm
      state: present

  - name: copy php to configuration file
    copy:
      src: /provisioning/setup/php.ini
      dest: /etc/php.ini
      owner: admin
      group: admin
      mode: 0644

  - name: Start service php
    service:
      name: php
      state: started

  - name: Start service php-fpm
    service:
      name: php-fpm
      state: started

  #MariaDB
  - name: install MariaDB
    package:
      name: MariaDB
      state: present

  - name: Configuring MariaDB Service
     service:
       name: mariadb.service
       state: restarted
     become: true

   - name: access to mysql
     shell: mysql -u root < /home/admin/mariadb_security_config.sql
     become: true

   - name: Configuring more MariaDB 
     service:
       name: mariadb
       state: restarted
     become: true

   - name: configure mariadb
     shell: mysql -u root -pP@ssw0rd < /home/admin/wp_mariadb_config.sql
     become: true

  #Wordpress
  - name: Get Wordpress
    get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
      mode: 0440

  - name: Unpack Wordpress
    unarchive:
      src: http://wordpress.org/latest.tar.gz
      dest: /home/admin
      remote_src: yes
      become: true
  
  - name: move the files to their final destination
    command: cat /etc/motd
    register: mymotd