- hosts: wp
  become: yes
  vars:
    mysql_root_password: P@ssw0rd
    mysql_root_password_update: yes

  tasks:
    #EPEL
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

    #firewall
    - firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes

    - firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Enable the firewall port 80
      firewalld:
       port: 80/tcp
       state: enabled
       immediate: yes

    - name: Enable the firewall port 443
      firewalld:
        port: 443/tcp
        state: enabled
        immediate: yes

    #nginx
    - name: install nginx
      package:
        name: nginx
        state: present

    - name: copy nginx to configuration file
      copy:
        src: ./setup/nginx.conf
        dest: /etc/nginx.conf
        owner: admin
        group: admin
        mode: 0644

    - name: Start service nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    #PHP
    - name: install php
      package:
        name: php
        state: present

    - name: install php-mysql
      package: 
        name: php-mysql
        state: present

    - name: install php-fpm
      package:
        name: php-fpm
        state: present

    - name: copy php to www.conf
      copy:
        src: ./setup/php.ini
        dest: /etc/php-fpm.d/www.conf
        owner: admin
        group: admin
        mode: 0644

    - name: copy php to php.ini
      copy:
        src: ./setup/php.ini
        dest: /etc/php-fpm.d/www.conf
        owner: admin
        group: admin
        mode: 0644

    - name: Start service php-fpm
      service:
        name: php-fpm
        state: started

    #MariaDB
    - name: install MariaDB
      package:
        name: mariadb
        state: present


    - name: installing mariadb-server
      package:
        name: mariadb-server
        state: present

    - name: Start mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: copying mariadb_security_config.sql
      copy:
        src: ./setup/mariadb_security_config.sql
        dest: /etc/mariadb_security_config.sql
        owner: admin
        group: admin
        mode: 0644

    - name: copying wp_mariadb_config.sql
      copy:
        src: ./setup/wp_mariadb_config.sql
        dest: /etc/wp_mariadb_config.sql
        owner: admin
        group: admin
        mode: 0644

    - name: run initial script for mariadb
      shell: mysql -u root < /etc/mariadb_security_config.sql

    - name: run second script for mariadb
      shell: mysql -u root < /etc/wp_mariadb_config.sql

    - name: restart mysql
      service:
        name: mariadb
        state: restarted
        enabled: yes

    #Wordpress
    - name: Get Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /usr/share/nginx/html/wordpress.tar.gz
        force: yes

    - name: Unpack Wordpress
      unarchive:
        src: /usr/share/nginx/html/wordpress.tar.gz
        dest:  /usr/share/nginx/html/
        copy: no
        creates: /usr/share/nginx/html/wordpress
    
    - name: copying wp-config
      copy:
        src: ./setup/wp-config.php
        dest: /usr/share/nginx/html/wp-config.php
        owner: admin
        group: admin
        mode: 0644

    - name: install rsync
      package:
        name: rsync
        state: present

    - name: rsync script for mariadb
      shell: rsync -avP /usr/share/nginx/html/wordpress/ /usr/share/nginx/html/